### ISSUE TITLE
upload rule example via http timeout

### ISSUE THREAD

**Issue by 0xwataru** [StamusNetworks/scirius-docker#2]
![image](https://user-images.githubusercontent.com/12377959/55695231-36e97680-59ea-11e9-831a-f067deada700.png)

**Comment by pevma** [comment]
Do you have access to the source? If you try downloading it from Scirius itself-  would it go ok ?

**Comment by hahadaxia** [comment]
yes i am in the docker，use the wget can get the tar file.
now i modify the  nginx and gunicorn -w $(($(nproc --all)*2+1)) -t 120*10 -b 0.0.0.0:8000 scirius.wsgi
set the timeout *10 ,but still have the problem

**Comment by 0xwataru** [comment]
> Do you have access to the source? If you try downloading it from Scirius itself- would it go ok ?

yes i am in the docker，use the wget can get the tar file.
now i modify the nginx and gunicorn -w $(($(nproc --all)2+1)) -t 1200 -b 0.0.0.0:8000 scirius.wsgi
set the timeout *10 ,but still have the problem
